pipeline:
  name: PipelineMVC
  identifier: PipelineMVC
  projectIdentifier: SampleProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: Service_1
            serviceDefinition:
              spec:
                variables: []
                manifests:
                  - manifest:
                      identifier: ManifestMVC
                      type: K8sManifest
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: GithubConnectorMN
                            gitFetchType: Branch
                            paths:
                              - resources
                            repoName: ff-golang-server-sdk
                            branch: main
                        valuesPaths:
                          - resources/metrics-v1.yaml
                        skipResourceVersioning: false
              type: Kubernetes
          execution:
            steps:
              - step:
                  type: K8sBlueGreenDeploy
                  name: stage deployment
                  identifier: stage_deployment
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
            rollbackSteps: []
          infrastructure:
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: harnessnadeem
                namespace: harness-delegate-ng
                releaseName: release-<+INFRA_KEY>
            environmentRef: Devlopement_environment
            allowSimultaneousDeployments: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
