pipeline:
  name: PipelineMVC
  identifier: PipelineMVC
  projectIdentifier: SampleProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: Service_1
            serviceDefinition:
              spec:
                variables: []
                manifests:
                  - manifest:
                      identifier: manidestkube
                      type: K8sManifest
                      spec:
                        store:
                          type: Git
                          spec:
                            connectorRef: GitKubeWebsiteConnector
                            gitFetchType: Branch
                            paths:
                              - content/en/examples/application/nginx-app.yaml
                            repoName: website
                            branch: main
                        skipResourceVersioning: false
              type: Kubernetes
          execution:
            steps:
              - step:
                  type: K8sBlueGreenDeploy
                  name: stage deployment
                  identifier: stage_deployment
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
              - step:
                  type: Verify
                  name: continuous verification
                  identifier: continuous_verification
                  spec:
                    type: Bluegreen
                    monitoredService:
                      type: Default
                      spec: {}
                    spec:
                      sensitivity: LOW
                      duration: 5m
                      deploymentTag: <+serviceConfig.artifacts.primary.tag>
                      failOnNoAnalysis: false
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Verification
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 2h
                            onTimeout:
                              action:
                                type: StageRollback
                    - onFailure:
                        errors:
                          - Unknown
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 2h
                            onTimeout:
                              action:
                                type: Ignore
            rollbackSteps: []
          infrastructure:
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: HarAzureConnector
                namespace: harness-delegate-ng
                releaseName: release-<+INFRA_KEY>
            environmentRef: Devlopement_environment
            allowSimultaneousDeployments: true
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - harnessazuredelegate
